---
- name: Install NodeJS v18
  hosts: localhost | all
  become: yes
  tasks:
    - name: Import the NodeSource GPG key
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add NodeJS 18.x repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install NodeJS
      apt:
        name: nodejs
        state: present
